name: Backend CI

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml
    - name: Run Tests
      run: mvn test --file backend/pom.xml