name: Backend CI

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Wait for MySQL to be ready
      run: sleep 20

    - name: Ensure resources directory and create application.properties
      run: |
        mkdir -p backend/src/main/resources
        echo "spring.datasource.url=jdbc:mysql://localhost:3306/testdb" >> backend/src/main/resources/application.properties
        echo "spring.datasource.username=testuser" >> backend/src/main/resources/application.properties
        echo "spring.datasource.password=testpass" >> backend/src/main/resources/application.properties
        echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> backend/src/main/resources/application.properties
        echo "spring.jpa.hibernate.ddl-auto=update" >> backend/src/main/resources/application.properties

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml

    - name: Run Tests
      run: mvn test --file backend/pom.xml
